version: '3'

networks:
  wordpress:

services:
  site:
    image: nginx:stable-alpine
    container_name: wp_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:8.0
    container_name: wp_mysql
    ports:
      - 3306:3306
    env_file: ./.env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp_php
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress